package modelo.basico;

public interface Entidade {

	/*
	 * ESSA E UMA INTERFACE MARCADORA
	 * NAO CARREGA NADA DENTRO DE SI
	 * SERVE SOMENTE COMO DE CONTROLE,
	 * ONDE SOMENTE AS CLASSES QUE IMPLEMENTAREM ENTIDADE PODERAO 
	 * TER ACESSO A DAO, AS CLASSES MODEL PRECISAM IMPLEMENTAR ENTIDADE...
	 * 
	 * CHAMA-SE MARCADORA POIS VISA MARCAR AS CLASSES QUE A IMPLEMENTAM
	 * E QUE TEM UMA FUNCAO EM COMUM
	 * 
	 */
	
}
